/* This file is automatically generated by `parse-sgf-list'.
 * Do not modify it, edit `sgf-undo-operations.list' instead.
 */


#include "sgf-undo.h"


const SgfUndoOperationInfo sgf_undo_operations[] = {
  { sgf_operation_delete_node,
    sgf_operation_add_node,
    sgf_operation_new_node_free_data },
  { sgf_operation_add_node,
    sgf_operation_delete_node,
    sgf_operation_delete_node_free_data },
  { sgf_operation_delete_node_children_undo,
    sgf_operation_delete_node_children_redo,
    sgf_operation_delete_node_children_free_data },
  { sgf_operation_swap_nodes_do_swap,
    sgf_operation_swap_nodes_do_swap,
    NULL },
  { sgf_operation_change_node_move_color_do_change,
    sgf_operation_change_node_move_color_do_change,
    NULL },
  { sgf_operation_change_node_to_play_color_do_change,
    sgf_operation_change_node_to_play_color_do_change,
    NULL },
  { sgf_operation_delete_property,
    sgf_operation_add_property,
    sgf_operation_new_property_free_data },
  { sgf_operation_add_property,
    sgf_operation_delete_property,
    sgf_operation_delete_property_free_data },
  { sgf_operation_change_property_do_change,
    sgf_operation_change_property_do_change,
    sgf_operation_change_property_free_data },
  { sgf_operation_change_real_property_do_change,
    sgf_operation_change_real_property_do_change,
    NULL },
  { sgf_operation_custom_undo,
    sgf_operation_custom_redo,
    sgf_operation_custom_free_data }
};
