/* This file is automatically generated by `parse-game-list'.
 * Do not modify it, edit `games.list' instead.
 */


#include "game-info.h"
#include "go.h"
#include "reversi.h"
#include "amazons.h"
#include <stdlib.h>


const GameInfo game_info[] = {
  /* Dummy entry, to fill zero index. */
  { NULL, 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[1], Go. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Go"), 19, "9\00013\00019\000", BLACK, NULL,
    go_is_game_over,
    "ABCDEFGHJKLMNOPQRSTUVWXYZ", 1,
    NULL, go_reset_game_data,
    go_is_legal_move, go_play_move, go_undo,
    go_apply_changes, go_add_dummy_move_entry,
    go_format_move, go_parse_move,
    go_validate_board, go_dump_board,
    sizeof (GoMoveStackEntry), 0.8 },

  /* trademark problems.) */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Reversi"), 8, "8\00010\000", BLACK, reversi_adjust_color_to_play,
    NULL,
    "ABCDEFGHIJKLMNOPQRSTUVWXY", 0,
    reversi_get_default_setup, NULL,
    reversi_is_legal_move, reversi_play_move, reversi_undo,
    reversi_apply_changes, reversi_add_dummy_move_entry,
    reversi_format_move, reversi_parse_move,
    reversi_validate_board, reversi_dump_board,
    sizeof (ReversiMoveStackEntry), 0.95 },

  /* GM[3], chess. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("chess"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[4], Gomoku + Renju. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Gomoku"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[5], Nine Men's Morris. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Nine Men's Morris"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[6], Backgammon. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Backgammon"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[7], Chinese chess. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Chinese chess"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[8], Shogi. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Shogi"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[9], Lines of Action. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Lines of Action"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[10], Ataxx. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Ataxx"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[11], Hex. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Hex"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[12], Jungle. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Jungle"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[13], Neutron. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Neutron"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[14], Philosopher's Football. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Philosopher's Football"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[15], Quadrature. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Quadrature"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[16], Trax. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Trax"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[17], Tantrix. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Tantrix"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[18], Amazons. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Amazons"), 10, "10\000", WHITE, amazons_adjust_color_to_play,
    amazons_is_game_over,
    "ABCDEFGHIJKLMNOPQRSTUVWXY", 1,
    amazons_get_default_setup, NULL,
    amazons_is_legal_move, amazons_play_move, amazons_undo,
    amazons_apply_changes, amazons_add_dummy_move_entry,
    amazons_format_move, amazons_parse_move,
    amazons_validate_board, amazons_dump_board,
    sizeof (AmazonsMoveStackEntry), 0.95 },

  /* GM[19], Octi. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Octi"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 },

  /* GM[20], Gess. */
  /* TRANSLATORS: Not important currently. */
  /* TRANSLATORS: Use your language's natural capitalization for the
     name of the game.  I.e. it doesn't have to start with a capital
     letter. */
  { N_("Gess"), 0, NULL, EMPTY, NULL,
    NULL,
    NULL, 0,
    NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    NULL, NULL,
    0, 0.0 }
};
