/* This file is automatically generated by `parse-configuration'.
 * Do not modify it, edit `markup-theme-configuration.list' instead.
 */


#include "markup-theme-configuration.h"
#include "utils.h"


static void	markup_theme_configuration_defaults_init (void *section_structure);


MarkupThemeList markup_themes = STATIC_MARKUP_THEME_LIST;


static const ConfigurationValue markup_theme_configuration_section_values[] = {
  { "Default markup size", VALUE_TYPE_REAL,
    STRUCTURE_FIELD_OFFSET (MarkupThemeListItem, default_size),
    NULL },
  { "Size is relative", VALUE_TYPE_BOOLEAN,
    STRUCTURE_FIELD_OFFSET (MarkupThemeListItem, size_is_relative),
    NULL },
  { "Default opacity", VALUE_TYPE_REAL,
    STRUCTURE_FIELD_OFFSET (MarkupThemeListItem, default_opacity),
    NULL }
};


const ConfigurationSection markup_theme_configuration_sections[] = {
  { "Markup Theme", 1,
    &markup_themes,
    markup_theme_configuration_defaults_init, string_list_empty,
    markup_theme_configuration_section_values,
    sizeof markup_theme_configuration_section_values / sizeof (ConfigurationValue) }
};


static void
markup_theme_configuration_defaults_init (void *section_structure)
{
  MarkupThemeListItem *structure = (MarkupThemeListItem *) section_structure;

  structure->directory		= NULL;
  structure->default_size	= 0.65;
  structure->size_is_relative	= 1;
  structure->default_opacity	= 1.0;
}


void
markup_theme_list_item_dispose (MarkupThemeListItem *item)
{
  utils_free (item->directory);
}
